name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t full-devops-project:ci .

      - name: Run container
        run: |
          docker run -d --name fd-server -p 3000:3000 full-devops-project:ci

      - name: Wait for service
        run: |
          for i in {1..20}; do
            if curl -sSf http://localhost:3000/ >/dev/null; then echo ok && break; fi
            sleep 1
          done

      - name: API smoke tests
        run: |
          set -e
          curl -s -X POST -H "Content-Type: application/json" -d '{"name":"CI Test","email":"ci@example.com"}' http://localhost:3000/api/users
          curl -s http://localhost:3000/api/users

      - name: Stop container
        if: always()
        run: |
          docker stop fd-server || true
          docker rm fd-server || true
